import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MyApp from "./_app";
import Header from "../components/header";
import Banner from "../components/banner/banner";
import bannerHome from "/public/images/banner-home.png"
import { Controller, Scene } from 'react-scrollmagic';
import Fade from "react-reveal/Fade";

export default function Home() {
  return (
      <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner title={"Healthy people, better humans"} backImage={bannerHome} cta={{url: '/demo', text: 'Solicita una demo'}}/>
      {/*<MyApp></MyApp>*/}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Fade bottom>
          <p>HOLAHOA</p>
        </Fade>


      </main>

      <footer className={styles.footer}>

      </footer>
      </>
  )
}
