import PostBanner from "../components/post-banner/post-banner";

export default function TerminosDeUso() {
  return (
      <>
        <PostBanner image={false} title={'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'}/>
        <section className="titleContent">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. A integer orci, fames aliquet elementum porttitor facilisi non. Felis non metus lobortis tincidunt tortor fermentum ligula. Justo lorem risus natoque facilisis lacinia blandit arcu ullamcorper. Id et ipsum orci nibh. Dui iaculis purus congue integer rhoncus faucibus.
            Amet quam sed risus, ornare. Nunc, ac sed sed pellentesque. Arcu fusce purus et est eu dolor, consequat in. Pellentesque eleifend elit ut fringilla maecenas. Nisi, dignissim at lobortis odio est sed cursus. Eget ut posuere congue quis odio. Blandit sed tortor egestas aliquam semper lectus eu nec ante. Massa nunc, ultrices pharetra egestas risus tristique elementum etiam. A elit sit in ut.</p>
          <p>Consequat scelerisque lacus venenatis, lacus. Tellus diam adipiscing metus nibh nisl suscipit quam. Faucibus fringilla eu pulvinar pulvinar neque elementum sed pellentesque. Nulla ullamcorper id ipsum leo faucibus. Imperdiet quam urna ornare ut varius aliquet lobortis. Sit aenean urna ac lectus et. Varius etiam porttitor sem eget auctor lacus, in fames mauris. A risus aenean nunc dolor nisi faucibus. Sit risus lorem interdum commodo.</p>
          <p>Mattis tortor consectetur dignissim morbi rhoncus. Purus est dui sit donec pharetra. Quam tortor quis id pellentesque risus euismod tortor, lectus. Aliquet non viverra dapibus mattis posuere elementum molestie egestas velit. Tempor eu nunc pharetra nulla vitae etiam in. Arcu cursus feugiat enim id ornare felis. Amet suscipit in sed aliquet duis. Velit penatibus non neque gravida amet aliquam morbi amet gravida. Diam vestibulum cursus est tortor, congue tincidunt facilisi arcu.</p>
          <p>Gravida et convallis eu leo. Morbi aenean nulla pharetra augue quis pellentesque semper mattis sed. Est felis nulla urna eget aliquet a egestas facilisis adipiscing. Maecenas a diam bibendum aliquam eleifend eros, eget eget. Tempus aliquam at eget duis cursus turpis diam. Eget quisque velit consectetur dapibus id tincidunt. Elementum aenean at mauris, pellentesque sapien, libero. Nunc, amet netus praesent curabitur in tempus enim interdum. Scelerisque gravida dui semper eu ultricies. Ac volutpat enim, ut at. Vitae felis odio etiam tellus volutpat, sociis venenatis sit fringilla. Nunc sed maecenas tristique non, dolor egestas gravida nibh. Nunc mauris, ut quis turpis vitae.</p>
          <p>Ullamcorper sit ut ornare arcu, vitae. Leo cursus magna risus habitasse pellentesque ipsum elementum augue. Eu, consequat, sapien, neque, vitae. Ut duis in sed volutpat dictum neque. Dolor convallis tristique arcu at. Gravida cursus rhoncus, tempus in proin habitasse eget. Venenatis massa egestas sagittis volutpat nibh. Consectetur erat enim rhoncus id ornare volutpat sem. At libero erat nunc nisl aliquet facilisis dolor, egestas. Dictum auctor potenti mi faucibus orci odio arcu. Morbi netus nulla euismod elementum ornare ac. Risus faucibus in aliquet leo mauris arcu viverra netus.</p>
          <p>Vel nibh erat vitae eget lorem urna. Viverra morbi in enim non pharetra aliquam habitant. Nunc in a sed at lectus. Duis odio dapibus ullamcorper platea imperdiet tortor elit. Hac vestibulum adipiscing leo nullam facilisis mattis elementum vel.</p>
        </section>
      </>
  )
}